name: flutter_mobx_form_validation_kit
description: Mobx flutter form control validation.
version: 2.0.0
author: quantumart (Vitalii Alferov)
homepage: https://github.com/QuantumArt/flutter_mobx_form_validation_kit

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  mobx: ^1.2.1+4


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.11
  mobx_codegen: ^1.1.2

flutter: