name: flutter_mobx_form_validation_kit
description: It is package for dynamic async validators form controls on Mobx.
version: 2.1.0+1
author: quantumart (Vitalii Alferov)
homepage: https://github.com/QuantumArt/flutter_mobx_form_validation_kit

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  mobx: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.12.2
  mobx_codegen: ^2.0.0

flutter: